#!/bin/bash

PREPROCESSOR=/usr/libexec/gcc/x86_64-linux-gnu/13/cc1
PROCESSED="false"
GET_OUTFILE="false"
OUTFILE=""
ARGS=()

for arg in "$@"; do
  if [[ "$arg" == "-E" ]]; then
    PROCESSED="true"
  elif [[ "$arg" == "-o" ]]; then
    GET_OUTFILE="true"
    continue
  elif [[ "$GET_OUTFILE" == "true" ]]; then
    GET_OUTFILE="false"
    OUTFILE=$arg
    continue
  fi

  ARGS+=("$arg")
done

if [[ $PROCESSED == "false" ]]; then
  $PREPROCESSOR $@
  exit $?
fi

echo "original args: [ $@ ]"
echo
echo "custom args: [ ${ARGS[@]} ]"
echo
echo

OUTPUT=$($PREPROCESSOR $@)
RESULT=$?
echo $OUTPUT

##cat $OUTFILE | sed 's/<struct squadmate>/_struct_squadmate/g' > $OUTFILE
##REPLACEMENT=$(cat $OUTFILE | sed 's/<struct squadmate>/_struct_squadmate/g')
#cat $OUTFILE | sed 's/<struct squadmate>/_struct_squadmate/g' > "$OUTFILE.c"
#rm $OUTFILE
#cp "$OUTFILE.c" $OUTFILE

exit $RESULT

#if [[ $PROCESSED == "true" ]]; then
#  echo "i am preprocessing to $OUTFILE"
#fi
#
#exit $?
