enum print_arg_types {
  PRINT_ARG_TYPE_CUSTOM,
  PRINT_ARG_TYPE_BOOL,
  PRINT_ARG_TYPE_CHAR,
  PRINT_ARG_TYPE_CHAR_UNSIGNED,
  PRINT_ARG_TYPE_INT,
  PRINT_ARG_TYPE_INT_UNSIGNED,
  PRINT_ARG_TYPE_DEC,
  PRINT_ARG_TYPE_CHAR_POINTER,
  PRINT_ARG_TYPE_VOID_POINTER,
};
