enum reflection_types {
  INT           = 1,
  DEC           = 2,
  STR           = 3,
  BOOL          = 4,
  CHAR          = 5,
  ENUM          = 6,
  STRUCT        = 7,
  ARRAY         = 8,
  POINTER       = 9,
  SELF          = 10,
  LIST          = 11,
  SET           = 12,
  MAP           = 13,
};
