#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Specify a source to compile."
    exit -1
fi

APP=$1
SOURCE=$1

gcc $SOURCE.c                 \
  -o $APP                     \
  -I ../../src                \
  -D ION_INCLUDED             \
  -Wall                       \
  -Wno-unused-label           \
  -Werror                     \
  ${@:2}
