#!/bin/bash
echo "Compiling $1.."
./compile $1 -O3 -march=native
#./compile $1 -g3
echo "Running $1.."
./$1 ${@:2}
#valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all ./$1 ${@:2}
echo
