#!/bin/bash

if [ "$1" = "recompile" ]; then
  cd ion
  ./compile > /dev/null 2>&1
  cd ..
  
  cd go
  ./compile > /dev/null 2>&1
  cd ..
  
  cd abseil
  ./compile > /dev/null 2>&1
  cd ..
fi

hyperfine --warmup 5 ion/ion go/go abseil/abseil
