#include "../../ion/modules/array.c"

#include "array/declinations.h"

#include "array/array_get/element_at_position.c"
//#include "array/array_get/position_out_of_bounds.c"
//#include "array/array_init/default_capacity.c"
//#include "array/array_init/immediate_allocation.c"
//#include "array/array_init/power_2_capacity.c"
//#include "array/array_pop/decrease_length.c"
//#include "array/array_pop/preserve_capacity.c"
//#include "array/array_push/increase_length.c"
//#include "array/array_push/increase_capacity.c"
//#include "array/array_set/element_at_position.c"
//#include "array/array_set/position_out_of_bounds.c"
