#include "../../ion/modules/binary.c"

#include "binary/binary_decode/array.c"
#include "binary/binary_decode/array_maxlength.c"
#include "binary/binary_decode/array_minlength.c"
#include "binary/binary_decode/pointer.c"
#include "binary/binary_decode/primitive.c"
#include "binary/binary_decode/sequence.c"
#include "binary/binary_decode/validator.c"
#include "binary/binary_decode/vector.c"
#include "binary/binary_decode/vector_maxlength.c"
#include "binary/binary_decode/vector_minlength.c"
#include "binary/binary_encode/array.c"
#include "binary/binary_encode/pointer.c"
#include "binary/binary_encode/primitive.c"
#include "binary/binary_encode/sequence.c"
#include "binary/binary_encode/vector.c"
#include "binary/binary_protocol/round_trip.c"
