#include "../../ion/modules/reflection.c"

#include "reflection/error_add_reflection_path/preserve_trace.c"
#include "reflection/reflection_path_print/dot_separated.c"
#include "reflection/reflection_path_print/empty.c"
#include "reflection/reflection_path_print/index.c"
#include "reflection/reflection_initialize/deep_propagation.c"
#include "reflection/reflection_initialize/link_target.c"
#include "reflection/reflection_macros/array_type.c"
#include "reflection/reflection_macros/array_type_limited.c"
#include "reflection/reflection_macros/array_type_nested.c"
#include "reflection/reflection_macros/sequence_type.c"
#include "reflection/reflection_macros/sequence_type_referenced.c"
#include "reflection/reflection_macros/sequence_type_tagless.c"
#include "reflection/reflection_macros/struct_type.c"
#include "reflection/reflection_macros/struct_type_defined.c"
#include "reflection/reflection_macros/struct_type_tagless.c"
#include "reflection/reflection_macros/vector_type.c"
