#include "../../ion/modules/tensor.c"

#include "tensor/tensor_at/correct_offsets.c"
#include "tensor/tensor_at_ranges/correct_offsets.c"
#include "tensor/tensor_at_sequences/correct_offsets.c"
#include "tensor/tensor_init/correct_dimensions.c"
#include "tensor/tensor_init/correct_length.c"
#include "tensor/tensor_init/correct_offsets.c"
#include "tensor/tensor_iterate_ranges/correct_positions.c"
#include "tensor/tensor_iterate_sequences/correct_positions.c"
