#include "functions/vector_allocate.c"
#include "functions/vector_equal.c"
#include "functions/vector_get.c"
#include "functions/vector_init.c"
#include "functions/vector_print.c"
#include "functions/vector_print_pretty.c"
#include "functions/vector_set.c"
