#include <ion/functions/array_allocate.h>
#include <ion/functions/array_get.h>
#include <ion/functions/array_init.h>
#include <ion/functions/array_last.h>
#include <ion/functions/array_pop.h>
#include <ion/functions/array_print.h>
#include <ion/functions/array_print_pretty.h>
#include <ion/functions/array_push.h>
#include <ion/functions/array_set.h>
#include <ion/functions/binary_decode.h>
#include <ion/functions/binary_decode_array.h>
#include <ion/functions/binary_decode_pointer.h>
#include <ion/functions/binary_decode_primitive.h>
#include <ion/functions/binary_decode_sequence.h>
#include <ion/functions/binary_decode_struct.h>
#include <ion/functions/binary_decode_vector.h>
#include <ion/functions/binary_encode.h>
#include <ion/functions/binary_encode_primitive.h>
#include <ion/functions/binary_encode_struct.h>
#include <ion/functions/date.h>
#include <ion/functions/date_to_string.h>
#include <ion/functions/date_today.h>
#include <ion/functions/hexdump.h>
#include <ion/functions/io_peek.h>
#include <ion/functions/io_read.h>
#include <ion/functions/io_read_file.h>
#include <ion/functions/io_read_memory.h>
#include <ion/functions/io_read_socket.h>
#include <ion/functions/io_write.h>
#include <ion/functions/io_write_file.h>
#include <ion/functions/io_write_memory.h>
#include <ion/functions/io_write_socket.h>
//#include <ion/functions/json_decode.h>
//#include <ion/functions/json_decode_number.h>
//#include <ion/functions/json_decode_spaces.h>
//#include <ion/functions/json_decode_struct.h>
//#include <ion/functions/json_parse_number.h>
//#include <ion/functions/json_parse_string.h>
#include <ion/functions/map_allocate.h>
#include <ion/functions/map_get.h>
#include <ion/functions/map_hash.h>
#include <ion/functions/map_init.h>
#include <ion/functions/map_print.h>
#include <ion/functions/map_rehash.h>
#include <ion/functions/map_set.h>
#include <ion/functions/map_set_rehash.h>
#include <ion/functions/memory_alloc.h>
#include <ion/functions/memory_alloc_zero.h>
#include <ion/functions/memory_init.h>
#include <ion/functions/memory_release.h>
#include <ion/functions/protocol_failure.h>
#include <ion/functions/protocol_path_print.h>
#include <ion/functions/range_set.h>
#include <ion/functions/reflect_print.h>
#include <ion/functions/reflect_print_indentation.h>
#include <ion/functions/reflect_typesize.h>
#include <ion/functions/reflect_validate.h>
#include <ion/functions/sci_notation_convert.h>
#include <ion/functions/tensor_allocate.h>
#include <ion/functions/tensor_at.h>
#include <ion/functions/tensor_at_ranges.h>
#include <ion/functions/tensor_at_sequences.h>
#include <ion/functions/tensor_init.h>
#include <ion/functions/tensor_iterate_ranges.h>
#include <ion/functions/tensor_iterate_sequences.h>
#include <ion/functions/time_now.h>
#include <ion/functions/time_to_string.h>
#include <ion/functions/vector_allocate.h>
#include <ion/functions/vector_equal.h>
#include <ion/functions/vector_get.h>
#include <ion/functions/vector_init.h>
#include <ion/functions/vector_print.h>
#include <ion/functions/vector_print_pretty.h>
#include <ion/functions/vector_set.h>
