#include "functions/alloc_resize.c"
#include "functions/alloc_resize_zero.c"
#include "functions/cmp.c"
//#include "functions/failure_add_io_info.c"
#include "functions/failure_add_reflection_info.c"
#include "functions/file_load.c"
#include "functions/hash.c"
#include "functions/hash_djb2.c"
#include "functions/hexdump.c"
//#include "functions/io_buffer_init.c"
//#include "functions/io_buffer_read.c"
//#include "functions/io_channel_read.c"
#include "functions/io_close.c"
//#include "functions/io_cursor_advance.c"
//#include "functions/io_cursor_restore.c"
//#include "functions/io_cursor_save.c"
//#include "functions/io_open_file.c"
//#include "functions/io_open_memory.c"
//#include "functions/io_open_pipe.c"
//#include "functions/io_open_socket.c"
//#include "functions/io_open_stream.c"
//#include "functions/io_open_string.c"
//#include "functions/io_peek.c"
#include "functions/io_init.c"
#include "functions/io_read.c"
#include "functions/memory_alloc.c"
#include "functions/memory_alloc_zero.c"
#include "functions/memory_init.c"
#include "functions/memory_release.c"
#include "functions/reflection_field_find.c"
#include "functions/reflection_path_print.c"
#include "functions/reflection_self_get.c"
#include "functions/reflection_validate.c"
#include "functions/signal_catcher.c"
#include "functions/string_char_at.c"
#include "functions/string_index.c"
#include "functions/string_starts.c"
#include "functions/substring.c"

#define T string
#include "functions/json.c"
#define T struct file
#include "functions/json.c"

#if platform(LINUX)
  #include "platform/linux/functions.c"
#endif
