#include <ion/functions/array_allocate.c>
#include <ion/functions/array_get.c>
#include <ion/functions/array_init.c>
#include <ion/functions/array_last.c>
#include <ion/functions/array_pop.c>
#include <ion/functions/array_print.c>
#include <ion/functions/array_print_pretty.c>
#include <ion/functions/array_push.c>
#include <ion/functions/array_set.c>
#include <ion/functions/binary_decode.c>
#include <ion/functions/binary_decode_array.c>
#include <ion/functions/binary_decode_pointer.c>
#include <ion/functions/binary_decode_primitive.c>
#include <ion/functions/binary_decode_sequence.c>
#include <ion/functions/binary_decode_struct.c>
#include <ion/functions/binary_decode_vector.c>
#include <ion/functions/binary_encode.c>
#include <ion/functions/binary_encode_array.c>
#include <ion/functions/binary_encode_primitive.c>
#include <ion/functions/binary_encode_struct.c>
#include <ion/functions/buffer_alloc.c>
#include <ion/functions/buffer_alloc_zero.c>
#include <ion/functions/buffer_data.c>
#include <ion/functions/buffer_init.c>
#include <ion/functions/buffer_release.c>
#include <ion/functions/date.c>
#include <ion/functions/date_to_string.c>
#include <ion/functions/date_today.c>
#include <ion/functions/hexdump.c>
#include <ion/functions/io_peek.c>
#include <ion/functions/io_read.c>
#include <ion/functions/io_read_file.c>
#include <ion/functions/io_read_memory.c>
#include <ion/functions/io_read_socket.c>
#include <ion/functions/io_write.c>
#include <ion/functions/io_write_file.c>
#include <ion/functions/io_write_memory.c>
#include <ion/functions/io_write_socket.c>
//#include <ion/functions/json_decode.c>
//#include <ion/functions/json_decode_number.c>
//#include <ion/functions/json_decode_spaces.c>
//#include <ion/functions/json_decode_struct.c>
//#include <ion/functions/json_parse_number.c>
//#include <ion/functions/json_parse_string.c>
#include <ion/functions/map_allocate.c>
#include <ion/functions/map_get.c>
#include <ion/functions/map_hash.c>
#include <ion/functions/map_init.c>
#include <ion/functions/map_print.c>
#include <ion/functions/map_rehash.c>
#include <ion/functions/map_set.c>
#include <ion/functions/map_set_rehash.c>
#include <ion/functions/memory_alloc.c>
#include <ion/functions/memory_alloc_zero.c>
#include <ion/functions/memory_init.c>
#include <ion/functions/memory_release.c>
#include <ion/functions/protocol_failure.c>
#include <ion/functions/protocol_path_print.c>
#include <ion/functions/range_set.c>
#include <ion/functions/reflect_print.c>
#include <ion/functions/reflect_print_indentation.c>
#include <ion/functions/reflect_typesize.c>
#include <ion/functions/reflect_validate.c>
#include <ion/functions/sci_notation_convert.c>
#include <ion/functions/tensor_allocate.c>
#include <ion/functions/tensor_at.c>
#include <ion/functions/tensor_at_ranges.c>
#include <ion/functions/tensor_at_sequences.c>
#include <ion/functions/tensor_init.c>
#include <ion/functions/tensor_iterate_ranges.c>
#include <ion/functions/tensor_iterate_sequences.c>
#include <ion/functions/time_now.c>
#include <ion/functions/time_to_string.c>
#include <ion/functions/vector_allocate.c>
#include <ion/functions/vector_equal.c>
#include <ion/functions/vector_get.c>
#include <ion/functions/vector_init.c>
#include <ion/functions/vector_print.c>
#include <ion/functions/vector_print_pretty.c>
#include <ion/functions/vector_set.c>
