#include "globals/date_string.h"
#include "globals/failure.h"
#include "globals/signal_received.h"
#include "globals/stderr.h"
#include "globals/stdin.h"
#include "globals/stdout.h"
#include "globals/time_string.h"
