//#include "functions/set_add.c"
#include "functions/set_alloc.c"
//#include "functions/set_del.c"
//#include "functions/set_each.c"
//#include "functions/set_has.c"
//#include "functions/set_init.c"
#include "functions/set_literal.c"
//#include "functions/set_pos.c"
//#include "functions/set_rehash.c"

//#include "functions/reflection/adder.c"
//#include "functions/reflection/creator.c"
