#include "functions/set_add.h"
#include "functions/set_alloc.h"
#include "functions/set_del.h"
#include "functions/set_each.h"
#include "functions/set_has.h"
#include "functions/set_init.h"
#include "functions/set_literal.h"
#include "functions/set_pos.h"
#include "functions/set_rehash.h"

//#include "functions/reflection/adder.h"
//#include "functions/reflection/creator.h"
