#include "functions/list_alloc.h"
#include "functions/list_at.h"
#include "functions/list_each.h"
#include "functions/list_init.h"
#include "functions/list_pop.h"
#include "functions/list_push.h"

#include "functions/list_alloc.c"
#include "functions/list_at.c"
#include "functions/list_each.c"
#include "functions/list_init.c"
#include "functions/list_pop.c"
#include "functions/list_push.c"
