#include <ion/functions/array_get.c>
#include <ion/functions/array_init.c>
#include <ion/functions/array_last.c>
#include <ion/functions/array_pop.c>
#include <ion/functions/array_print.c>
#include <ion/functions/array_push.c>
#include <ion/functions/array_set.c>
#include <ion/functions/binary_decode.c>
#include <ion/functions/binary_decode_array.c>
#include <ion/functions/binary_decode_pointer.c>
#include <ion/functions/binary_decode_primitive.c>
#include <ion/functions/binary_decode_sequence.c>
#include <ion/functions/binary_decode_struct.c>
//#include <ion/functions/binary_encode.c>
#include <ion/functions/hexdump.c>
#include <ion/functions/io_peek.c>
#include <ion/functions/io_read.c>
#include <ion/functions/io_write.c>
//#include <ion/functions/json_decode.c>
//#include <ion/functions/json_decode_number.c>
//#include <ion/functions/json_decode_spaces.c>
//#include <ion/functions/json_decode_struct.c>
//#include <ion/functions/json_parse_number.c>
//#include <ion/functions/json_parse_string.c>
#include <ion/functions/map_get.c>
#include <ion/functions/map_hash.c>
#include <ion/functions/map_init.c>
#include <ion/functions/map_print.c>
#include <ion/functions/map_rehash.c>
#include <ion/functions/map_set.c>
#include <ion/functions/memory_alloc.c>
#include <ion/functions/memory_alloc_zero.c>
#include <ion/functions/memory_init.c>
#include <ion/functions/memory_release.c>
#include <ion/functions/protocol_failure.c>
#include <ion/functions/protocol_path_print.c>
#include <ion/functions/reflect_typesize.c>
#include <ion/functions/sci_notation_convert.c>
