#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <immintrin.h>
#include <limits.h>
#include <math.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <ion/headers/typedefs.h>
#include <ion/headers/constants.h>
#include <ion/headers/enums.h>
#include <ion/headers/macros.h>
#include <ion/headers/structs.h>
#include <ion/headers/globals.h>

#include <ion/headers/functions/array_get.h>
#include <ion/headers/functions/array_init.h>
#include <ion/headers/functions/array_last.h>
#include <ion/headers/functions/array_pop.h>
#include <ion/headers/functions/array_print.h>
#include <ion/headers/functions/array_push.h>
#include <ion/headers/functions/array_set.h>
#include <ion/headers/functions/binary_decode.h>
#include <ion/headers/functions/binary_decode_array.h>
#include <ion/headers/functions/binary_decode_pointer.h>
#include <ion/headers/functions/binary_decode_primitive.h>
#include <ion/headers/functions/binary_decode_sequence.h>
#include <ion/headers/functions/binary_decode_struct.h>
//#include <ion/headers/functions/binary_encode.h>
#include <ion/headers/functions/hexdump.h>
#include <ion/headers/functions/io_peek.h>
#include <ion/headers/functions/io_read.h>
#include <ion/headers/functions/io_read_file.h>
#include <ion/headers/functions/io_read_memory.h>
#include <ion/headers/functions/io_read_socket.h>
#include <ion/headers/functions/io_write.h>
//#include <ion/headers/functions/json_decode.h>
//#include <ion/headers/functions/json_decode_number.h>
//#include <ion/headers/functions/json_decode_spaces.h>
//#include <ion/headers/functions/json_decode_struct.h>
//#include <ion/headers/functions/json_parse_number.h>
//#include <ion/headers/functions/json_parse_string.h>
#include <ion/headers/functions/map_get.h>
#include <ion/headers/functions/map_hash.h>
#include <ion/headers/functions/map_init.h>
#include <ion/headers/functions/map_print.h>
#include <ion/headers/functions/map_rehash.h>
#include <ion/headers/functions/map_set.h>
#include <ion/headers/functions/map_set_rehash.h>
#include <ion/headers/functions/memory_alloc.h>
#include <ion/headers/functions/memory_alloc_zero.h>
#include <ion/headers/functions/memory_init.h>
#include <ion/headers/functions/memory_release.h>
#include <ion/headers/functions/protocol_failure.h>
#include <ion/headers/functions/protocol_path_print.h>
#include <ion/headers/functions/reflect_typesize.h>
#include <ion/headers/functions/sci_notation_convert.h>
